output: Barbarian.o BlueMen.o Character.o Die.o Game.o HarryPotter.o main.o Medusa.o Menu.o Queue.o Stack.o Validate.o Vampire.o
	g++ Barbarian.o BlueMen.o Character.o Die.o Game.o HarryPotter.o main.o Medusa.o Menu.o Queue.o Stack.o Validate.o Vampire.o -o output

Barbarian.o: Barbarian.cpp Barbarian.hpp
	g++ -c -std=c++11 Barbarian.cpp

BlueMen.o: BlueMen.cpp BlueMen.hpp
	g++ -c -std=c++11 BlueMen.cpp

Character.o: Character.cpp Character.hpp
	g++ -c -std=c++11 Character.cpp

Die.o: Die.cpp Die.hpp
	g++ -c -std=c++11 Die.cpp

Game.o: Game.cpp Game.hpp
	g++ -c -std=c++11 Game.cpp

HarryPotter.o: HarryPotter.cpp HarryPotter.hpp
	g++ -c -std=c++11 HarryPotter.cpp

main.o: main.cpp
	g++ -c -std=c++11 main.cpp

Medusa.o: Medusa.cpp Medusa.hpp
	g++ -c -std=c++11 Medusa.cpp

Menu.o: Menu.cpp Menu.hpp
	g++ -c -std=c++11 Menu.cpp

Queue.o: Queue.cpp Queue.hpp
	g++ -c -std=c++11 Queue.cpp

Stack.o: Stack.cpp Stack.hpp
	g++ -c -std=c++11 Stack.cpp

Validate.o: Validate.cpp Validate.hpp
	g++ -c -std=c++11 Validate.cpp

Vampire.o: Vampire.cpp Vampire.hpp
	g++ -c -std=c++11 Vampire.cpp

clean:
	rm *.o

