output: Armor.o ArmorSpace.o ChainmailArmor.o EarthMonster.o EarthStone.o EmptySpace.o FireStone.o Game.o HealthSpace.o Hero.o LeatherArmor.o main.o FireMonster.o Menu.o Monster.o Elements.o MonsterSpace.o PlateArmor.o Space.o SpaceTypes.o SpellStone.o SpellStoneSpace.o PaceSpace.o WaterMonster.o WaterStone.o WindMonster.o WindStone.o
	g++ Armor.o ArmorSpace.o ChainmailArmor.o EarthMonster.o EarthStone.o EmptySpace.o FireStone.o Game.o HealthSpace.o Hero.o LeatherArmor.o main.o FireMonster.o Menu.o Monster.o Elements.o MonsterSpace.o PlateArmor.o Space.o SpaceTypes.o SpellStone.o SpellStoneSpace.o PaceSpace.o WaterMonster.o WaterStone.o WindMonster.o WindStone.o -o output

Armor.o: Armor.hpp Armor.cpp
	g++ -c -std=c++11 Armor.cpp

ArmorSpace.o: ArmorSpace.hpp ArmorSpace.cpp
	g++ -c -std=c++11 ArmorSpace.cpp

ChainmailArmor.o: ChainmailArmor.hpp ChainmailArmor.cpp
	g++ -c -std=c++11 ChainmailArmor.cpp

EarthMonster.o: EarthMonster.hpp EarthMonster.cpp
	g++ -c -std=c++11 EarthMonster.cpp

EarthStone.o: EarthStone.hpp EarthStone.cpp
	g++ -c -std=c++11 EarthStone.cpp

EmptySpace.o: EmptySpace.hpp EmptySpace.cpp
	g++ -c -std=c++11 EmptySpace.cpp

FireStone.o: FireStone.hpp FireStone.cpp
	g++ -c -std=c++11 FireStone.cpp

Game.o: Game.hpp Game.cpp
	g++ -c -std=c++11 Game.cpp

HealthSpace.o: HealthSpace.hpp HealthSpace.cpp
	g++ -c -std=c++11 HealthSpace.cpp

Hero.o: Hero.hpp Hero.cpp
	g++ -c -std=c++11 Hero.cpp

LeatherArmor.o: LeatherArmor.hpp LeatherArmor.cpp
	g++ -c -std=c++11 LeatherArmor.cpp

main.o: main.cpp
	g++ -c -std=c++11 main.cpp

FireMonster.o: FireMonster.hpp FireMonster.cpp
	g++ -c -std=c++11 FireMonster.cpp

Menu.o: Menu.hpp Menu.cpp
	g++ -c -std=c++11 Menu.cpp

Monster.o: Monster.hpp Monster.cpp
	g++ -c -std=c++11 Monster.cpp

Elements.o: Elements.hpp Elements.cpp
	g++ -c -std=c++11 Elements.cpp

MonsterSpace.o: MonsterSpace.hpp MonsterSpace.cpp
	g++ -c -std=c++11 MonsterSpace.cpp

PlateArmor.o: PlateArmor.hpp PlateArmor.cpp
	g++ -c -std=c++11 PlateArmor.cpp

Space.o: Space.hpp Space.cpp
	g++ -c -std=c++11 Space.cpp

SpaceTypes.o: SpaceTypes.hpp SpaceTypes.cpp
	g++ -c -std=c++11 SpaceTypes.cpp

SpellStone.o: SpellStone.hpp SpellStone.cpp
	g++ -c -std=c++11 SpellStone.cpp

SpellStoneSpace.o: SpellStoneSpace.hpp SpellStoneSpace.cpp
	g++ -c -std=c++11 SpellStoneSpace.cpp

PaceSpace.o: PaceSpace.hpp PaceSpace.cpp
	g++ -c -std=c++11 PaceSpace.cpp

WaterMonster.o: WaterMonster.hpp WaterMonster.cpp
	g++ -c -std=c++11 WaterMonster.cpp

WaterStone.o: WaterStone.hpp WaterStone.cpp
	g++ -c -std=c++11 WaterStone.cpp

WindMonster.o: WindMonster.hpp WindMonster.cpp
	g++ -c -std=c++11 WindMonster.cpp

WindStone.o: WindStone.hpp WindStone.cpp
	g++ -c -std=c++11 WindStone.cpp

clean:
	rm *.o

